config/routes.rb
Rails.application.routes.draw do
  root 'restaurants#index'

  resources :restaurants

  delete "restaurants/:id" => "restaurants#destroy", as: :delete_restaurant 

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.destroy
      redirect_to '/'
    else
      render 'show'
    end
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to '/'
    else
      render 'new'
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to '/'
    else
      render 'edit'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  private
  def restaurant_params
    params.require(:restaurant).permit([:name,:location,:cuisine,:rating])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DinersApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
<div>
  <%= f.label(:name) %>
  <%= f.text_field(:name) %>
</div>
<div>
  <%= f.label(:location) %>
  <%= f.text_field(:location) %>
</div>
<div>
  <%= f.label(:cuisine) %>
  <%= f.text_field(:cuisine) %>
</div>
<div>
  <%= f.label(:rating) %>
  <%= f.number_field(:rating) %>
</div>
<%= f.submit("Submit") %>
<% end %>

app/views/restaurants/edit.html.erb
<h1> Editor </h1>
<%= render "form" %>

app/views/restaurants/index.html.erb
<h1>Restaurants!! :)</h1>
<% @restaurants.each do |r| %>
<div class="diner">

<h2>Restaurant Name: <%= link_to r.name, restaurant_path(r)%></h2></div>


<% end %>

app/views/restaurants/new.html.erb
<h1>Create A New Restaurant</h1>
<%= render "form" %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<ul>
  <li><%= @restaurant.location %></li>
  <li><%= @restaurant.cuisine %></li>
  <li><%= @restaurant.rating %></li>
</ul>

<%= link_to 'Update Restaurant', edit_restaurant_path(@restaurant)  %>
<%= link_to 'Delete Restaurant', delete_restaurant_path(@restaurant), method: :delete %>